# Generated by Django 6.0.3 on 2026-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songgenerationrequest',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('romantic', 'Romantic'), ('excited', 'Excited'), ('calm', 'Calm'), ('nostalgic', 'Nostalgic'), ('inspirational', 'Inspirational')], max_length=50),
        ),
        migrations.AlterField(
            model_name='songgenerationrequest',
            name='occasion',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('anniversary', 'Anniversary'), ('graduation', 'Graduation'), ('christmas', 'Christmas'), ('party', 'Party'), ('farewell', 'Farewell')], max_length=50),
        ),
        migrations.AlterField(
            model_name='songgenerationrequest',
            name='singer_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], max_length=50),
        ),
    ]
