# Generated by Django 6.0.3 on 2026-03-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='library',
        ),
        migrations.AddField(
            model_name='songlibrary',
            name='songs',
            field=models.ManyToManyField(blank=True, to='songs.song'),
        ),
    ]
